// React/src/App.js
import React from 'react';
import { BrowserRouter, Switch, Route } from 'react-router-dom'
import './App.css'
import Navbar from './components/Navbar'
import FeatureImage from './components/FeatureImage'
import Search from './components/Search';
import Ranking from './components/Ranking';

function App(props) {
  return (
    <div className="App">
      <BrowserRouter>
        <Navbar />
        <Switch>
          <Route exact path="/">
            <FeatureImage 
              title="About my name"
              text="As coisas mais legais sobre seu nome diretamente do site do IBGE."
            />
            <Ranking title="Nomes mais comuns do Brasil" />
          </Route>
          <Route exact path={`/pesquisar`}>
            <Search />
          </Route>
        </Switch>
      </BrowserRouter>
    </div>
  );
}

export default App;

// Vue/src/App.vue
<template>
  <v-app>
    <v-main>
      <Navbar :appTitle="appTitle"/>
      <FeatureImage :title="title" :description="description"/>
      <Search />
    </v-main>
  </v-app>
</template>

<script>
import Navbar from './components/Navbar';
import FeatureImage from './components/FeatureImage';
import Search from './components/Search';

export default {
  name: 'App',

  components: {
    Navbar,
    FeatureImage,
    Search,
  },

  data: () => ({
    appTitle: 'Home',
    title: 'About my name',
    description: 'Informe seu nome e encontre as coisas mais legais sobre ele diretamente do site do IBGE'
  }),
};
</script>

<style>
    body {
      background-color: #f5f5f5;
      color: #282828;
    }
</style>
