// Vue/src/components/Search.vue
<template>
  <Form :title="this.title" :description="this.description"/>
</template>

<script>
import Form from './Form';

export default {
  name: 'Search',

  components: {
    Form,
  },

  data: () => ({
    title: 'O que o IBGE diz sobre seu nome?',
    description: 'Digite-o e descubra.'
  }),
};
</script>

// React/src/components/Search.js
import React, { useState } from 'react'
import ContainerForm from './ContainerForm'


const Search = (props) => {
    const [nome, setNome] = useState('');

    const getNome = (novoNome) => {
        setNome(novoNome);
    }

    return (
        <ContainerForm 
            text="O que o IBGE diz sobre seu nome?"
            getNome={getNome}
        />
    )
}

export default Search;
